version: '3.8'

services:
  # Web UI サービス
  web-ui:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api-server
    networks:
      - todo-network

  # API Server サービス
  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=todos
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_DEBUG=false
    depends_on:
      - mysql
    networks:
      - todo-network

  # MySQL データベース
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=todos
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todo-network

volumes:
  mysql_data:

networks:
  todo-network:
    driver: bridge
